aws:
  region: 'eu-west-1'
  artifact_bucket: 'shootr-releases'

path_in_docker: '/ci'
docker_build_image_name: java8-ci-slim
mvn_build_args: 'jacoco:report coveralls:report'

default_deploy: false
default_test_and_build: true
default_docker_build: false
default_docker_tag: false
default_docker_tag_value: ''
default_upload_to_s3: false
default_deploy_type: elb

branch_config:
  - branch: '^develop$'
    asg: asg-shootr-api-tst
    deploy: true
    deploy_type: elb
    test_and_build: true
    docker_build: true
    docker_tag: true
    docker_tag_value: 'TST'
    upload_to_s3: true
    backoffice_url: tst-backoffice.shootr.com

  - branch: '^master$'
    asg: asg-shootr-api-pre
    deploy: true
    deploy_type: elb
    test_and_build: false
    docker_build: false
    docker_tag: true
    docker_tag_value: 'PRE'
    upload_to_s3: false
    backoffice_url: null

  - branch: '^pro-'
    asg: asg-shootr-api-pro
    deploy: true
    deploy_type: elb
    test_and_build: false
    docker_build: false
    docker_tag: true
    docker_tag_value: 'PRO'
    upload_to_s3: false
    backoffice_url: backoffice.shootr.com

  - branch: '^prohotfix-'
    asg: asg-shootr-api-pro
    deploy: true
    deploy_type: elb
    test_and_build: true
    docker_build: true
    docker_tag: true
    docker_tag_value: 'PRO'
    upload_to_s3: true
    backoffice_url: backoffice.shootr.com

  - branch: '^dev-'
    asg: asg-shootr-api-dev
    deploy_type: targetGroup
    deploy: true
    test_and_build: true
    docker_build: true
    docker_tag: true
    docker_tag_value: 'DEV'
    upload_to_s3: true
    backoffice_url: null
